// A representative list rather than the full ISO-3166 set, covering the
// markets GO MO Group's contact form is realistically filled out from.
export const COUNTRIES = [
  'Sweden',
  'United Kingdom',
  'India',
  'United States',
  'Germany',
  'Norway',
  'Denmark',
  'Finland',
  'Netherlands',
  'France',
  'Spain',
  'Italy',
  'Switzerland',
  'Austria',
  'Belgium',
  'Ireland',
  'Poland',
  'Portugal',
  'Canada',
  'Australia',
  'Singapore',
  'United Arab Emirates',
  'Saudi Arabia',
  'Japan',
  'China',
  'South Korea',
  'Brazil',
  'Mexico',
  'South Africa',
  'Other',
]
